export enum HuobiOrderTypeEnum {
  BUY_MARKET = 'buy-market',
  SELL_MARKET = 'sell-market',
  BUY_LIMIT = 'buy-limit',
  SELL_LIMIT = 'sell-limit',
  BUY_IOC = 'buy-ioc',
  SELL_IOC = 'sell-ioc',
  BUY_LIMIT_MAKER = 'buy-limit-maker',
  SELL_LIMIT_MAKER = 'sell-limit-maker',
  BUY_STOP_LIMIT = 'buy-stop-limit',
  SELL_STOP_LIMIT = 'sell-stop-limit',
  BUY_LIMIT_FOK = 'buy-limit-fok',
  SELL_LIMIT_FOK = 'sell-limit-fok',
  BUY_STOP_LIMIT_FOK = 'buy-stop-limit-fok',
  SELL_STOP_LIMIT_FOK = 'sell-stop-limit-fok',
  STOP_LIMIT = 'limit',
  STOP_MARKET = 'market',
}
