import { AlunaAccountEnum } from '../../../lib/enums/AlunaAccountEnum'
import { AlunaOrderStatusEnum } from '../../../lib/enums/AlunaOrderStatusEnum'
import { AlunaOrderTypesEnum } from '../../../lib/enums/AlunaOrderTypesEnum'
import { AlunaSideEnum } from '../../../lib/enums/AlunaSideEnum'
import { IAlunaOrderSchema } from '../../../lib/schemas/IAlunaOrderSchema'
import { BitmexOrderStatusEnum } from '../enums/BitmexOrderStatusEnum'
import { BitmexOrderTypeEnum } from '../enums/BitmexOrderTypeEnum'
import { BitmexSideEnum } from '../enums/BitmexSideEnum'
import { IBitmexOrderSchema } from '../schemas/IBitmexOrderSchema'



export const BITMEX_RAW_ORDERS: IBitmexOrderSchema[] = [
  {
    orderID: 'dae99a67-66c7-4645-a16c-e51465438a92',
    clOrdID: '',
    clOrdLinkID: '',
    account: 393293,
    symbol: 'ADAUSD',
    side: 'Buy' as BitmexSideEnum,
    simpleOrderQty: null,
    orderQty: 1,
    price: 0.828,
    displayQty: null,
    stopPx: null,
    pegOffsetValue: null,
    pegPriceType: '',
    currency: 'USD',
    settlCurrency: 'XBt',
    ordType: 'Limit' as BitmexOrderTypeEnum,
    timeInForce: 'GoodTillCancel',
    execInst: '',
    contingencyType: '',
    exDestination: 'XBME',
    ordStatus: 'New' as BitmexOrderStatusEnum,
    triggered: '',
    workingIndicator: true,
    ordRejReason: '',
    simpleLeavesQty: null,
    leavesQty: 1,
    simpleCumQty: null,
    cumQty: 0,
    avgPx: null,
    multiLegReportingType: 'SingleSecurity',
    text: 'Submission from testnet.bitmex.com',
    transactTime: '2022-02-23T11:19:35.183Z',
    timestamp: '2022-02-23T11:19:35.183Z',
  },
  {
    orderID: 'e4766f5d-8ef3-48e1-804c-d3022cd6c89c',
    clOrdID: '',
    clOrdLinkID: '',
    account: 393293,
    symbol: 'XBTUSD',
    side: 'Buy' as BitmexSideEnum,
    simpleOrderQty: null,
    orderQty: 100,
    price: 35000,
    displayQty: null,
    stopPx: null,
    pegOffsetValue: null,
    pegPriceType: '',
    currency: 'USD',
    settlCurrency: 'XBt',
    ordType: 'Market' as BitmexOrderTypeEnum,
    timeInForce: 'GoodTillCancel',
    execInst: '',
    contingencyType: '',
    exDestination: 'XBME',
    ordStatus: 'Filled' as BitmexOrderStatusEnum,
    triggered: '',
    workingIndicator: true,
    ordRejReason: '',
    simpleLeavesQty: null,
    leavesQty: 100,
    simpleCumQty: null,
    cumQty: 0,
    avgPx: null,
    multiLegReportingType: 'SingleSecurity',
    text: 'Submission from testnet.bitmex.com',
    transactTime: '2022-02-23T12:02:52.163Z',
    timestamp: '2022-02-23T12:02:52.163Z',
  },
  {
    orderID: 'f9bb2487-2a12-4e84-9136-ecb5e7ba932f',
    clOrdID: '',
    clOrdLinkID: '',
    account: 393293,
    symbol: 'XBTEUR',
    side: 'Sell' as BitmexSideEnum,
    simpleOrderQty: null,
    orderQty: 100,
    price: null,
    displayQty: null,
    stopPx: 38000,
    pegOffsetValue: null,
    pegPriceType: '',
    currency: 'EUR',
    settlCurrency: 'XBt',
    ordType: 'Stop' as BitmexOrderTypeEnum,
    timeInForce: 'GoodTillCancel',
    execInst: '',
    contingencyType: '',
    exDestination: 'XBME',
    ordStatus: 'New' as BitmexOrderStatusEnum,
    triggered: '',
    workingIndicator: true,
    ordRejReason: '',
    simpleLeavesQty: null,
    leavesQty: 100,
    simpleCumQty: null,
    cumQty: 0,
    avgPx: null,
    multiLegReportingType: 'SingleSecurity',
    text: 'Submission from testnet.bitmex.com',
    transactTime: '2022-02-23T12:03:05.920Z',
    timestamp: '2022-02-23T12:03:05.920Z',
  },
  {
    orderID: '20618405-3a15-4d10-8657-35fd206ea66e',
    clOrdID: '',
    clOrdLinkID: '',
    account: 393293,
    symbol: 'ETHUSDTH22',
    side: 'Buy' as BitmexSideEnum,
    simpleOrderQty: null,
    orderQty: 1000,
    price: 2300,
    displayQty: null,
    stopPx: 2500,
    pegOffsetValue: null,
    pegPriceType: '',
    currency: 'USDT',
    settlCurrency: 'USDt',
    ordType: 'StopLimit' as BitmexOrderTypeEnum,
    timeInForce: 'GoodTillCancel',
    execInst: '',
    contingencyType: '',
    exDestination: 'XBME',
    ordStatus: 'New' as BitmexOrderStatusEnum,
    triggered: 'StopOrderTriggered',
    workingIndicator: true,
    ordRejReason: '',
    simpleLeavesQty: null,
    leavesQty: 1000,
    simpleCumQty: null,
    cumQty: 0,
    avgPx: null,
    multiLegReportingType: 'SingleSecurity',
    text: 'Submission from testnet.bitmex.com',
    transactTime: '2022-02-23T12:03:19.633Z',
    timestamp: '2022-02-23T12:03:19.633Z',
  },
  {
    orderID: '7f30dd9a-9a31-4815-a21b-be959698cc8f',
    clOrdID: '',
    clOrdLinkID: '',
    account: 393293,
    symbol: 'XBTUSDT',
    side: 'Buy' as BitmexSideEnum,
    simpleOrderQty: null,
    orderQty: 1000,
    price: 31715,
    displayQty: null,
    stopPx: null,
    pegOffsetValue: null,
    pegPriceType: '',
    currency: 'USDT',
    settlCurrency: 'USDt',
    ordType: 'Limit' as BitmexOrderTypeEnum,
    timeInForce: 'GoodTillCancel',
    execInst: '',
    contingencyType: '',
    exDestination: 'XBME',
    ordStatus: 'Canceled' as BitmexOrderStatusEnum,
    triggered: '',
    workingIndicator: true,
    ordRejReason: '',
    simpleLeavesQty: null,
    leavesQty: 1000,
    simpleCumQty: null,
    cumQty: 0,
    avgPx: null,
    multiLegReportingType: 'SingleSecurity',
    text: 'Submission from testnet.bitmex.com',
    transactTime: '2022-02-23T12:04:19.388Z',
    timestamp: '2022-02-23T12:04:19.388Z',
  },
  {
    orderID: 'f07b969b-a02a-4949-ad73-70a47625d853',
    clOrdID: '',
    clOrdLinkID: '',
    account: 393293,
    symbol: 'ETHH22',
    side: 'Sell' as BitmexSideEnum,
    simpleOrderQty: null,
    orderQty: 1000,
    price: 0.08912,
    displayQty: null,
    stopPx: null,
    pegOffsetValue: null,
    pegPriceType: '',
    currency: 'XBT',
    settlCurrency: 'XBt',
    ordType: 'Limit' as BitmexOrderTypeEnum,
    timeInForce: 'GoodTillCancel',
    execInst: '',
    contingencyType: '',
    exDestination: 'XBME',
    ordStatus: 'PartiallyFilled' as BitmexOrderStatusEnum,
    triggered: '',
    workingIndicator: true,
    ordRejReason: '',
    simpleLeavesQty: null,
    leavesQty: 1000,
    simpleCumQty: null,
    cumQty: 0,
    avgPx: null,
    multiLegReportingType: 'SingleSecurity',
    text: 'Submission from testnet.bitmex.com',
    transactTime: '2022-02-23T12:03:37.080Z',
    timestamp: '2022-02-23T12:03:37.080Z',
  },
]



export const BITMEX_PARSED_ORDERS: IAlunaOrderSchema[] = [
  {
    id: '0029380b-38e6-4517-92d0-1ae85b97c3fa',
    symbolPair: 'ADAUSDT',
    baseSymbolId: 'ADA',
    quoteSymbolId: 'USDT',
    exchangeId: 'bitmex',
    account: 'derivatives' as AlunaAccountEnum,
    type: 'limit' as AlunaOrderTypesEnum,
    amount: 70,
    total: 38.934,
    status: 'open' as AlunaOrderStatusEnum,
    side: 'long' as AlunaSideEnum,
    rate: 0.5562,
    stopRate: undefined,
    limitRate: undefined,
    uiCustomDisplay: {
      amount: { symbolId: 'ADA', value: 70 },
      total: { symbolId: 'USDT', value: 38.934 },
      rate: { symbolId: 'USDT', value: 0.5562 },
    },
    placedAt: new Date('2022-02-24T00:55:53.094Z'),
    filledAt: undefined,
    canceledAt: undefined,
    meta: {
      orderID: '0029380b-38e6-4517-92d0-1ae85b97c3fa',
      clOrdID: '',
      clOrdLinkID: '',
      account: 393293,
      symbol: 'ADAUSDT',
      side: 'Buy',
      simpleOrderQty: null,
      orderQty: 7000,
      price: 0.5562,
      displayQty: null,
      stopPx: null,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USDT',
      settlCurrency: 'USDt',
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      execInst: '',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: true,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 7000,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'Submission from testnet.bitmex.com',
      transactTime: '2022-02-24T00:55:53.094Z',
      timestamp: '2022-02-24T00:55:53.094Z',
    },
  },
  {
    id: '6292ea86-2f69-4d40-bce9-c8b65012bad5',
    symbolPair: 'ADAUSD',
    baseSymbolId: 'ADA',
    quoteSymbolId: 'USD',
    exchangeId: 'bitmex',
    account: 'derivatives' as AlunaAccountEnum,
    type: 'limit' as AlunaOrderTypesEnum,
    amount: 3,
    total: 7.285256482856184,
    status: 'open' as AlunaOrderStatusEnum,
    side: 'long' as AlunaSideEnum,
    rate: 0.6573,
    stopRate: undefined,
    limitRate: undefined,
    uiCustomDisplay: {
      amount: { symbolId: 'Cont', value: 3 },
      total: { symbolId: 'XBT', value: 0.00019719 },
      rate: { symbolId: 'USD', value: 0.6573 },
    },
    placedAt: new Date('2022-02-24T00:56:06.914Z'),
    filledAt: undefined,
    canceledAt: undefined,
    meta: {
      orderID: '6292ea86-2f69-4d40-bce9-c8b65012bad5',
      clOrdID: '',
      clOrdLinkID: '',
      account: 393293,
      symbol: 'ADAUSD',
      side: 'Buy',
      simpleOrderQty: null,
      orderQty: 3,
      price: 0.6573,
      displayQty: null,
      stopPx: null,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USD',
      settlCurrency: 'XBt',
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      execInst: '',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: true,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 3,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'Submission from testnet.bitmex.com',
      transactTime: '2022-02-24T00:56:06.914Z',
      timestamp: '2022-02-24T00:56:06.914Z',
    },
  },
  {
    id: '96ca46b6-16db-469d-b21d-55394659eb8a',
    symbolPair: 'ETHUSD',
    baseSymbolId: 'ETH',
    quoteSymbolId: 'USD',
    exchangeId: 'bitmex',
    account: 'derivatives' as AlunaAccountEnum,
    type: 'limit' as AlunaOrderTypesEnum,
    amount: 1,
    total: 72.44670804507149,
    status: 'open' as AlunaOrderStatusEnum,
    side: 'long' as AlunaSideEnum,
    rate: 1963.6,
    stopRate: undefined,
    limitRate: undefined,
    uiCustomDisplay: {
      amount: { symbolId: 'Cont', value: 1 },
      total: { symbolId: 'XBT', value: 0.0019636 },
      rate: { symbolId: 'USD', value: 1963.6 },
    },
    placedAt: new Date('2022-02-24T00:56:20.610Z'),
    filledAt: undefined,
    canceledAt: undefined,
    meta: {
      orderID: '96ca46b6-16db-469d-b21d-55394659eb8a',
      clOrdID: '',
      clOrdLinkID: '',
      account: 393293,
      symbol: 'ETHUSD',
      side: 'Buy',
      simpleOrderQty: null,
      orderQty: 1,
      price: 1963.6,
      displayQty: null,
      stopPx: null,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USD',
      settlCurrency: 'XBt',
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      execInst: '',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: true,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 1,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'Submission from testnet.bitmex.com',
      transactTime: '2022-02-24T00:56:20.610Z',
      timestamp: '2022-02-24T00:56:20.610Z',
    },
  },
  {
    id: 'e8151fa3-3cb6-48c8-82b1-c47f2c11aef3',
    symbolPair: 'LUNAUSD',
    baseSymbolId: 'LUNA',
    quoteSymbolId: 'USD',
    exchangeId: 'bitmex',
    account: 'derivatives' as AlunaAccountEnum,
    type: 'stop-market' as AlunaOrderTypesEnum,
    amount: 2,
    total: 43.84776096170627,
    status: 'open' as AlunaOrderStatusEnum,
    side: 'long' as AlunaSideEnum,
    rate: undefined,
    stopRate: 59.444,
    limitRate: undefined,
    uiCustomDisplay: {
      amount: { symbolId: 'Cont', value: 2 },
      total: { symbolId: 'XBT', value: 0.00118888 },
      stopRate: { symbolId: 'USD', value: 59.444 },
    },
    placedAt: new Date('2022-02-24T00:56:52.002Z'),
    filledAt: undefined,
    canceledAt: undefined,
    meta: {
      orderID: 'e8151fa3-3cb6-48c8-82b1-c47f2c11aef3',
      clOrdID: '',
      clOrdLinkID: '',
      account: 393293,
      symbol: 'LUNAUSD',
      side: 'Buy',
      simpleOrderQty: null,
      orderQty: 2,
      price: null,
      displayQty: null,
      stopPx: 59.444,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USD',
      settlCurrency: 'XBt',
      ordType: 'Stop',
      timeInForce: 'ImmediateOrCancel',
      execInst: 'Close,LastPrice',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: false,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 2,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'Submission from testnet.bitmex.com',
      transactTime: '2022-02-24T00:56:52.002Z',
      timestamp: '2022-02-24T00:56:52.002Z',
    },
  },
  {
    id: '166566c7-8884-4df2-ba1e-e2f33787fbe5',
    symbolPair: 'DOGEUSD',
    baseSymbolId: 'DOGE',
    quoteSymbolId: 'USD',
    exchangeId: 'bitmex',
    account: 'derivatives' as AlunaAccountEnum,
    type: 'stop-limit' as AlunaOrderTypesEnum,
    amount: 7,
    total: 27.515853792925245,
    status: 'open' as AlunaOrderStatusEnum,
    side: 'short' as AlunaSideEnum,
    rate: undefined,
    stopRate: 0.11633,
    limitRate: 0.10634,
    uiCustomDisplay: {
      amount: { symbolId: 'Cont', value: 7 },
      total: { symbolId: 'XBT', value: 0.00074438 },
      stopRate: { symbolId: 'USD', value: 0.11633 },
      limitRate: { symbolId: 'USD', value: 0.10634 },
    },
    placedAt: new Date('2022-02-24T00:57:31.265Z'),
    filledAt: undefined,
    canceledAt: undefined,
    meta: {
      orderID: '166566c7-8884-4df2-ba1e-e2f33787fbe5',
      clOrdID: '',
      clOrdLinkID: '',
      account: 393293,
      symbol: 'DOGEUSD',
      side: 'Sell',
      simpleOrderQty: null,
      orderQty: 7,
      price: 0.10634,
      displayQty: null,
      stopPx: 0.11633,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USD',
      settlCurrency: 'XBt',
      ordType: 'StopLimit',
      timeInForce: 'GoodTillCancel',
      execInst: 'Close,LastPrice',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: false,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 7,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'Submission from testnet.bitmex.com',
      transactTime: '2022-02-24T00:57:31.265Z',
      timestamp: '2022-02-24T00:57:31.265Z',
    },
  },
  {
    id: 'dcca0f6e-df0b-4c19-9122-205c5b6b3458',
    symbolPair: 'XBTUSD',
    baseSymbolId: 'XBT',
    quoteSymbolId: 'USD',
    exchangeId: 'bitmex',
    account: 'derivatives' as AlunaAccountEnum,
    type: 'limit' as AlunaOrderTypesEnum,
    amount: 0.003050501044796608,
    total: 100,
    status: 'open' as AlunaOrderStatusEnum,
    side: 'long' as AlunaSideEnum,
    rate: 32781.5,
    stopRate: undefined,
    limitRate: undefined,
    uiCustomDisplay: {
      amount: { symbolId: 'USD', value: 100 },
      total: { symbolId: 'XBT', value: 0.003050501044796608 },
      rate: { symbolId: 'USD', value: 32781.5 },
    },
    placedAt: new Date('2022-02-24T00:57:49.851Z'),
    filledAt: undefined,
    canceledAt: undefined,
    meta: {
      orderID: 'dcca0f6e-df0b-4c19-9122-205c5b6b3458',
      clOrdID: '',
      clOrdLinkID: '',
      account: 393293,
      symbol: 'XBTUSD',
      side: 'Buy',
      simpleOrderQty: null,
      orderQty: 100,
      price: 32781.5,
      displayQty: null,
      stopPx: null,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USD',
      settlCurrency: 'XBt',
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      execInst: '',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: true,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 100,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'Submission from testnet.bitmex.com',
      transactTime: '2022-02-24T00:57:49.851Z',
      timestamp: '2022-02-24T00:57:49.851Z',
    },
  },
  {
    id: '0b67b16b-f108-455b-a77a-fa8ce358a1f2',
    symbolPair: 'SOLUSDT',
    baseSymbolId: 'SOL',
    quoteSymbolId: 'USDT',
    exchangeId: 'bitmex',
    account: 'derivatives' as AlunaAccountEnum,
    type: 'limit' as AlunaOrderTypesEnum,
    amount: 0.4,
    total: 22.2,
    status: 'open' as AlunaOrderStatusEnum,
    side: 'long' as AlunaSideEnum,
    rate: 55.5,
    stopRate: undefined,
    limitRate: undefined,
    uiCustomDisplay: {
      amount: { symbolId: 'SOL', value: 0.4 },
      total: { symbolId: 'USDT', value: 22.2 },
      rate: { symbolId: 'USDT', value: 55.5 },
    },
    placedAt: new Date('2022-02-24T00:58:11.959Z'),
    filledAt: undefined,
    canceledAt: undefined,
    meta: {
      orderID: '0b67b16b-f108-455b-a77a-fa8ce358a1f2',
      clOrdID: '',
      clOrdLinkID: '',
      account: 393293,
      symbol: 'SOLUSDT',
      side: 'Buy',
      simpleOrderQty: null,
      orderQty: 4000,
      price: 55.5,
      displayQty: null,
      stopPx: null,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USDT',
      settlCurrency: 'USDt',
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      execInst: '',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: true,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 4000,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'Submission from testnet.bitmex.com',
      transactTime: '2022-02-24T00:58:11.959Z',
      timestamp: '2022-02-24T00:58:11.959Z',
    },
  },
]
