import { AlunaAccountEnum } from '../../../lib/enums/AlunaAccountEnum'
import { IAlunaBalanceSchema } from '../../../lib/schemas/IAlunaBalanceSchema'
import { IBitmexBalanceSchema } from '../schemas/IBitmexBalanceSchema'



export const BITMEX_RAW_BALANCES: IBitmexBalanceSchema[] = [
  {
    account: 777,
    currency: 'XBt',
    riskLimit: 1000000000000,
    prevState: '',
    state: '',
    action: '',
    amount: 492116,
    pendingCredit: 0,
    pendingDebit: 0,
    confirmedDebit: 0,
    prevRealisedPnl: 0,
    prevUnrealisedPnl: 0,
    grossComm: 0,
    grossOpenCost: 0,
    grossOpenPremium: 0,
    grossExecCost: 0,
    grossMarkValue: 0,
    riskValue: 0,
    taxableMargin: 0,
    initMargin: 0,
    maintMargin: 0,
    sessionMargin: 0,
    targetExcessMargin: 0,
    varMargin: 0,
    realisedPnl: 0,
    unrealisedPnl: 0,
    indicativeTax: 0,
    unrealisedProfit: 0,
    syntheticMargin: null,
    walletBalance: 492116,
    marginBalance: 492116,
    marginBalancePcnt: 1,
    marginLeverage: 0,
    marginUsedPcnt: 0,
    excessMargin: 492116,
    excessMarginPcnt: 1,
    availableMargin: 492116,
    withdrawableMargin: 492116,
    grossLastValue: 0,
    commission: null,
    makerFeeDiscount: null,
    takerFeeDiscount: null,
    timestamp: '2022-02-15T12:00:00.274Z',
  },
  {
    account: 777,
    currency: 'USDt',
    riskLimit: 500000000000000,
    prevState: '',
    state: '',
    action: '',
    amount: 0,
    pendingCredit: 0,
    pendingDebit: 0,
    confirmedDebit: 0,
    prevRealisedPnl: 0,
    prevUnrealisedPnl: 0,
    grossComm: 0,
    grossOpenCost: 0,
    grossOpenPremium: 0,
    grossExecCost: 0,
    grossMarkValue: 0,
    riskValue: 0,
    taxableMargin: 0,
    initMargin: 0,
    maintMargin: 0,
    sessionMargin: 0,
    targetExcessMargin: 0,
    varMargin: 0,
    realisedPnl: 0,
    unrealisedPnl: 0,
    indicativeTax: 0,
    unrealisedProfit: 0,
    syntheticMargin: null,
    walletBalance: 0,
    marginBalance: 0,
    marginBalancePcnt: 1,
    marginLeverage: 0,
    marginUsedPcnt: 0,
    excessMargin: 0,
    excessMarginPcnt: 1,
    availableMargin: 0,
    withdrawableMargin: 0,
    grossLastValue: 0,
    commission: null,
    makerFeeDiscount: null,
    takerFeeDiscount: null,
    timestamp: '2022-02-13T20:00:00.083Z',
  },
  {
    account: 777,
    currency: 'BMEx',
    riskLimit: null,
    prevState: '',
    state: '',
    action: '',
    amount: 7800000,
    pendingCredit: 0,
    pendingDebit: 0,
    confirmedDebit: 0,
    prevRealisedPnl: 0,
    prevUnrealisedPnl: 0,
    grossComm: 0,
    grossOpenCost: 0,
    grossOpenPremium: 0,
    grossExecCost: 0,
    grossMarkValue: 0,
    riskValue: 0,
    taxableMargin: 0,
    initMargin: 0,
    maintMargin: 0,
    sessionMargin: 0,
    targetExcessMargin: 0,
    varMargin: 0,
    realisedPnl: 0,
    unrealisedPnl: 0,
    indicativeTax: 0,
    unrealisedProfit: 0,
    syntheticMargin: null,
    walletBalance: 7800000,
    marginBalance: 7800000,
    marginBalancePcnt: 1,
    marginLeverage: 0,
    marginUsedPcnt: 0,
    excessMargin: 7800000,
    excessMarginPcnt: 1,
    availableMargin: 7800000,
    withdrawableMargin: 7800000,
    grossLastValue: 0,
    commission: null,
    makerFeeDiscount: null,
    takerFeeDiscount: null,
    timestamp: '2022-02-15T07:35:07.149Z',
  },
]



export const BITMEX_PARSED_BALANCES: IAlunaBalanceSchema[] = [
  {
    symbolId: 'BTC',
    account: 'derivatives' as AlunaAccountEnum,
    available: 0.00492116,
    total: 0.00492116,
    meta: {
      account: 1766960,
      currency: 'XBt',
      riskLimit: 1000000000000,
      prevState: '',
      state: '',
      action: '',
      amount: 492116,
      pendingCredit: 0,
      pendingDebit: 0,
      confirmedDebit: 0,
      prevRealisedPnl: 0,
      prevUnrealisedPnl: 0,
      grossComm: 0,
      grossOpenCost: 0,
      grossOpenPremium: 0,
      grossExecCost: 0,
      grossMarkValue: 0,
      riskValue: 0,
      taxableMargin: 0,
      initMargin: 0,
      maintMargin: 0,
      sessionMargin: 0,
      targetExcessMargin: 0,
      varMargin: 0,
      realisedPnl: 0,
      unrealisedPnl: 0,
      indicativeTax: 0,
      unrealisedProfit: 0,
      syntheticMargin: null,
      walletBalance: 492116,
      marginBalance: 492116,
      marginBalancePcnt: 1,
      marginLeverage: 0,
      marginUsedPcnt: 0,
      excessMargin: 492116,
      excessMarginPcnt: 1,
      availableMargin: 492116,
      withdrawableMargin: 492116,
      grossLastValue: 0,
      commission: null,
      makerFeeDiscount: null,
      takerFeeDiscount: null,
      timestamp: '2022-02-15T12:00:00.274Z',
    },
  },
  {
    symbolId: 'USDT',
    account: 'derivatives' as AlunaAccountEnum,
    available: 60,
    total: 90,
    meta: {
      account: 1766960,
      currency: 'USDt',
      riskLimit: 500000000000000,
      prevState: '',
      state: '',
      action: '',
      amount: 0,
      pendingCredit: 0,
      pendingDebit: 0,
      confirmedDebit: 0,
      prevRealisedPnl: 0,
      prevUnrealisedPnl: 0,
      grossComm: 0,
      grossOpenCost: 0,
      grossOpenPremium: 0,
      grossExecCost: 0,
      grossMarkValue: 0,
      riskValue: 0,
      taxableMargin: 0,
      initMargin: 0,
      maintMargin: 0,
      sessionMargin: 0,
      targetExcessMargin: 0,
      varMargin: 0,
      realisedPnl: 0,
      unrealisedPnl: 0,
      indicativeTax: 0,
      unrealisedProfit: 0,
      syntheticMargin: null,
      walletBalance: 0,
      marginBalance: 0,
      marginBalancePcnt: 1,
      marginLeverage: 0,
      marginUsedPcnt: 0,
      excessMargin: 0,
      excessMarginPcnt: 1,
      availableMargin: 0,
      withdrawableMargin: 0,
      grossLastValue: 0,
      commission: null,
      makerFeeDiscount: null,
      takerFeeDiscount: null,
      timestamp: '2022-02-13T20:00:00.083Z',
    },
  },
  {
    symbolId: 'BMEx',
    account: 'derivatives' as AlunaAccountEnum,
    available: 7800000,
    total: 7800000,
    meta: {
      account: 1766960,
      currency: 'BMEx',
      riskLimit: null,
      prevState: '',
      state: '',
      action: '',
      amount: 7800000,
      pendingCredit: 0,
      pendingDebit: 0,
      confirmedDebit: 0,
      prevRealisedPnl: 0,
      prevUnrealisedPnl: 0,
      grossComm: 0,
      grossOpenCost: 0,
      grossOpenPremium: 0,
      grossExecCost: 0,
      grossMarkValue: 0,
      riskValue: 0,
      taxableMargin: 0,
      initMargin: 0,
      maintMargin: 0,
      sessionMargin: 0,
      targetExcessMargin: 0,
      varMargin: 0,
      realisedPnl: 0,
      unrealisedPnl: 0,
      indicativeTax: 0,
      unrealisedProfit: 0,
      syntheticMargin: null,
      walletBalance: 7800000,
      marginBalance: 7800000,
      marginBalancePcnt: 1,
      marginLeverage: 0,
      marginUsedPcnt: 0,
      excessMargin: 7800000,
      excessMarginPcnt: 1,
      availableMargin: 7800000,
      withdrawableMargin: 7800000,
      grossLastValue: 0,
      commission: null,
      makerFeeDiscount: null,
      takerFeeDiscount: null,
      timestamp: '2022-02-15T07:35:07.149Z',
    },
  },
]
