export enum BitfinexOrderStatusEnum {
  ACTIVE = 'ACTIVE',
  EXECUTED = 'EXECUTED',
  CANCELED = 'CANCELED',
  PARTIALLY_FILLED = 'PARTIALLY FILLED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT BALANCE',
}
